# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: see-grub
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    #   - arm64
    # overrides:
    #   - goos: linux
    #     goarch: arm64
    #     env:
    #       - CGO_ENABLED=1
    #       - CC=aarch64-linux-gnu-gcc

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

aurs:
  - name: see-grub-bin
    homepage: https://github.com/Uami-11/see-grub
    description: "see-grub is a renderer for grub theme.txts made with Go and Ebitengine"
    maintainers:
      - "Uami-11 <nirwan.m.9618@gmail.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/see-grub-bin.git"
    url_template: "https://github.com/Uami-11/see-grub/releases/download/{{ .Tag }}/see-grub_Linux_x86_64.tar.gz"
    commit_author:
      name: Uami-11
      email: nirwan.m.9618@gmail.com
    skip_upload: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: Uami-11
    name: see-grub
  draft: false
  prerelease: auto
  footer: >-
    ---
    Maintained by [@Uami-11](https://github.com/Uami-11).
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
